version: "3.1"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - /home/d3vr10/dev/dbs:/opt
    environment:
      - POSTGRES_PASSWORD=testing
